name: Lint Markdown Files

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.3.0

    - name: Set up Node.js
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install markdownlint-cli --save-dev

    - name: Lint markdown files
      continue-on-error: true
      run: |
        npx markdownlint --ignore node_modules --disable MD013 -- '**/*.md' -o markdownlint_result.json
        if [ $? -ne 0 ]; then
          echo "::error::Markdown linting failed"
          exit 1
        fi

    - name: Report linting results
      id: results
      uses: actions/upload-artifact@v3.1.2
      with:
        name: lint-report.json
        path: markdownlint_result.json
        
    - name: Comment on pull request
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6.4.0
      with:
        script: |
          const lintErrors = steps.lint.outputs.stderr || '';
          const lintResultsLink = steps.results.outputs.artifact_url;
          const pullRequestNumber = github.event.number;

          const commentBody = `
          ## Markdown Lint Results
          ${lintResultsLink}
          ## Lint Errors
          ${lintErrors}
          `;

          const response = await github.pulls.createReview({
            owner: github.repository.owner.login,
            repo: github.repository.name,
            pull_number: pullRequestNumber,
            body: commentBody,
            event: "COMMENT"
          });

          console.log(response.data);
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
