name: Lint Markdown Files

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.3.0

    - name: Set up Node.js
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install markdownlint-cli --save-dev

    - name: Lint markdown files
      continue-on-error: true
      run: |
        npx markdownlint --ignore node_modules --disable MD013 -- '**/*.md' 
       
    - name: Store output and Upload artifact
      id: results
      if: ${{ failure() }}
      run: |
        echo 'Error: Markdown Lint failed'
        echo "::error file=markdownlint_result.json::$(cat markdownlint_result.json)"
        echo ::set-output name=error::$(cat markdownlint_result.json)
        echo ::set-output name=artifact_url::${{ steps.results.outputs.artifact_url }}

    - name: Comment on pull request
      if: github.event_name == 'pull_request'
      uses: thollander/actions-comment-pull-request@v2.3.1
      with:
        message: |
          ## Markdown Lint Results
          ${{ steps.results.outputs.artifact_url }}
          ## Lint Errors
          ${{ steps.results.outputs.error }}
        access-token: ${{ secrets.GITHUB_TOKEN }}
