name: Lint Markdown Files

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions: 
      pull-requests: write 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.3.0

    - name: Set up Node.js
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install markdownlint-cli --save-dev

    - name: Lint markdown files
      id: lint
      continue-on-error: true
      run: |
        npx markdownlint --ignore node_modules --disable MD013 -- '**/*.md' > markdownlint_result.txt || true
        echo ::set-output name=error::$(cat markdownlint_result.txt)
        echo ::set-output name=file::markdownlint_result.txt
        echo ::set-output name=file_url::https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/markdownlint_result.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Comment on pull request
      if: github.event_name == 'pull_request'
      uses: thollander/actions-comment-pull-request@v2.3.1
      with:
        pull-request-number: "${{ github.event.pull_request.number }}"
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        message: |
          ## Markdown Lint Results
          ${{ steps.lint.outputs.file_url }}
          
          ## Lint Errors
          ```
          ${{ steps.lint.outputs.error }}
          ```
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

